export enum SubscriptionStatus {
  CONSENT_REJECTED = 'CONSENT_REJECTED',
  CONSENT_FAILED = 'CONSENT_FAILED',
  ACTIVE = 'ACTIVE',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  ACTIVATION_FAILED = 'ACTIVATION_FAILED',
  CANCELLED = 'CANCELLED',
}

export enum SubscriptionEvent {
  SUBSCRIPTION_INITIAL = 'SUBSCRIPTION_INITIAL',
  SUBSCRIPTION_ON_DEMAND = 'SUBSCRIPTION_ON_DEMAND',
}

export enum RedirectionStatus {
  SUCCESS = 'SUCCEEDED',
  FAIL = 'FAILED',
  CANCEL = 'CANCELLED',
}
