export enum SubscriptionStatus {
  CONSENT_REJECTED = 'CONSENT_REJECTED',
  CONSENT_FAILED = 'CONSENT_FAILED',
  ACTIVE = 'ACTIVE',
  PENDING_ACTIVATION = 'PENDING_ACTIVATION',
  ACTIVATION_FAILED = 'ACTIVATION_FAILED',
}
